In [2]:
import pandas as pd

In [6]:
idx1 = pd.Index([1,3,5,7,9])
idx2 = pd.Index([2,3,5,7,11])

idx1.intersection(idx2)

Index([3, 5, 7], dtype='int64')

In [7]:
idx1.union(idx2)

Index([1, 2, 3, 5, 7, 9, 11], dtype='int64')

In [11]:
df = pd.read_csv("https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv")
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [12]:
col1 = df['sepal_length']
type(col1)

pandas.core.series.Series

In [13]:
col1 = df['sepal_length']
col2 = df['sepal_width']

In [14]:
pd.DataFrame({'sepal_length':col1,
              'sepal_width':col2})

     sepal_length  sepal_width
0             5.1          3.5
1             4.9          3.0
2             4.7          3.2
3             4.6          3.1
4             5.0          3.6
..            ...          ...
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[150 rows x 2 columns]

In [ ]:
df.columns = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species']

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [19]:
df.sepal_length = df['sepal_length']

In [21]:
df['aaa'] = df['sepal_length'] - df['sepal_width']

In [22]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species  aaa
0           5.1          3.5           1.4          0.2  setosa  1.6
1           4.9          3.0           1.4          0.2  setosa  1.9
2           4.7          3.2           1.3          0.2  setosa  1.5
3           4.6          3.1           1.5          0.2  setosa  1.5
4           5.0          3.6           1.4          0.2  setosa  1.4

In [38]:
df['sepal_length', 'species']

KeyError: ('sepal_length', 'species')

In [46]:
df.iloc[:20,:4]

    sepal_length  sepal_width  petal_length  petal_width
0            5.1          3.5           1.4          0.2
1            4.9          3.0           1.4          0.2
2            4.7          3.2           1.3          0.2
3            4.6          3.1           1.5          0.2
4            5.0          3.6           1.4          0.2
5            5.4          3.9           1.7          0.4
6            4.6          3.4           1.4          0.3
7            5.0          3.4           1.5          0.2
8            4.4          2.9           1.4          0.2
9            4.9          3.1           1.5          0.1
10           5.4          3.7           1.5          0.2
11           4.8          3.4           1.6          0.2
12           4.8          3.0           1.4          0.1
13           4.3          3.0           1.1          0.1
14           5.8          4.0           1.2          0.2
15           5.7          4.4           1.5          0.4
16           5.4          3.9           1.3          0.4
17           5.1          3.5           1.4          0.3
18           5.7          3.8           1.7          0.3
19           5.1          3.8           1.5          0.3

In [47]:
df.loc[:,'sepal_length':'petal_length']

     sepal_length  sepal_width  petal_length
0             5.1          3.5           1.4
1             4.9          3.0           1.4
2             4.7          3.2           1.3
3             4.6          3.1           1.5
4             5.0          3.6           1.4
..            ...          ...           ...
145           6.7          3.0           5.2
146           6.3          2.5           5.0
147           6.5          3.0           5.2
148           6.2          3.4           5.4
149           5.9          3.0           5.1

[150 rows x 3 columns]

In [ ]:
df.loc[:, [2,4]]

KeyError: "None of [Index([2, 4], dtype='int64')] are in the [columns]"

In [52]:
df[:1]

   sepal_length  sepal_width  petal_length  petal_width species  aaa
0           5.1          3.5           1.4          0.2  setosa  1.6

In [56]:
mask = df.sepal_length >5
df[mask]

     sepal_length  sepal_width  petal_length  petal_width    species  aaa
0             5.1          3.5           1.4          0.2     setosa  1.6
5             5.4          3.9           1.7          0.4     setosa  1.5
10            5.4          3.7           1.5          0.2     setosa  1.7
14            5.8          4.0           1.2          0.2     setosa  1.8
15            5.7          4.4           1.5          0.4     setosa  1.3
..            ...          ...           ...          ...        ...  ...
145           6.7          3.0           5.2          2.3  virginica  3.7
146           6.3          2.5           5.0          1.9  virginica  3.8
147           6.5          3.0           5.2          2.0  virginica  3.5
148           6.2          3.4           5.4          2.3  virginica  2.8
149           5.9          3.0           5.1          1.8  virginica  2.9

[118 rows x 6 columns]

In [57]:
df.iloc[:20,[1, 3, 5]]

    sepal_width  petal_width  aaa
0           3.5          0.2  1.6
1           3.0          0.2  1.9
2           3.2          0.2  1.5
3           3.1          0.2  1.5
4           3.6          0.2  1.4
5           3.9          0.4  1.5
6           3.4          0.3  1.2
7           3.4          0.2  1.6
8           2.9          0.2  1.5
9           3.1          0.1  1.8
10          3.7          0.2  1.7
11          3.4          0.2  1.4
12          3.0          0.1  1.8
13          3.0          0.1  1.3
14          4.0          0.2  1.8
15          4.4          0.4  1.3
16          3.9          0.4  1.5
17          3.5          0.3  1.6
18          3.8          0.3  1.9
19          3.8          0.3  1.3

In [61]:
df.sepal_length +1

0      6.1
1      5.9
2      5.7
3      5.6
4      6.0
      ...
145    7.7
146    7.3
147    7.5
148    7.2
149    6.9
Name: sepal_length, Length: 150, dtype: float64

new_df = df.iloc[:,:4]

In [62]:
new_df = df.iloc[:,:4].copy()

In [63]:
new_df

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [65]:
import numpy as np

np.exp(new_df) / 4

     sepal_length  sepal_width  petal_length  petal_width
0       41.005477     8.278863      1.013800     0.305351
1       33.572445     5.021384      1.013800     0.305351
2       27.486793     6.133133      0.917324     0.305351
3       24.871079     5.549488      1.120422     0.305351
4       37.103290     9.149559      1.013800     0.305351
..            ...          ...           ...          ...
145    203.101456     5.021384     45.318060     2.493546
146    136.142978     3.045623     37.103290     1.671474
147    166.285408     5.021384     45.318060     1.847264
148    123.187260     7.491025     55.351604     2.493546
149     91.259367     5.021384     41.005477     1.512412

[150 rows x 4 columns]

In [67]:
new_df.head()

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [73]:
new_df['sepal_length'][1:] / new_df['sepal_width'] #join의 개념 index를 기준으로 계산

0           NaN
1      1.633333
2      1.468750
3      1.483871
4      1.388889
         ...
145    2.233333
146    2.520000
147    2.166667
148    1.823529
149    1.966667
Length: 150, dtype: float64

In [74]:
new_df['sepal_length'][1:].add(new_df['sepal_width'], fill_value=0)

0      3.5
1      7.9
2      7.9
3      7.7
4      8.6
      ...
145    9.7
146    8.8
147    9.5
148    9.6
149    8.9
Length: 150, dtype: float64

In [ ]:
np.random.random(149) / np.random.random(150) # 안되는게 정상

ValueError: operands could not be broadcast together with shapes (149,) (150,)

In [76]:
np.sum(new_df.isna())

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
dtype: int64

In [81]:
new_df['sepal_length']

0      5.1
1      4.9
2      4.7
3      NaN
4      5.0
      ...
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [82]:
new_df.isna()

     sepal_length  sepal_width  petal_length  petal_width
0           False        False         False        False
1           False        False         False        False
2           False        False         False        False
3            True        False         False        False
4           False        False         False        False
..            ...          ...           ...          ...
145         False        False         False        False
146         False        False         False        False
147         False        False         False        False
148         False        False         False        False
149         False        False         False        False

[150 rows x 4 columns]

df = read.csv('') # 읽기

df.head() # Head 출력

df.info() # 전체 정보 읽기

In [84]:
new_df.notna()

     sepal_length  sepal_width  petal_length  petal_width
0            True         True          True         True
1            True         True          True         True
2            True         True          True         True
3           False         True          True         True
4            True         True          True         True
..            ...          ...           ...          ...
145          True         True          True         True
146          True         True          True         True
147          True         True          True         True
148          True         True          True         True
149          True         True          True         True

[150 rows x 4 columns]

In [ ]:
new_df.dropna() # 원본은 바뀌지 않음
new_df2 = new_df.dropna() # 이렇게 해야지 new_df2에 적용된 값을 넣고 new_df2로 작업 진행

In [87]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  149 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB

In [90]:
new_df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 149 entries, 0 to 149
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  149 non-null    float64
 1   sepal_width   149 non-null    float64
 2   petal_length  149 non-null    float64
 3   petal_width   149 non-null    float64
dtypes: float64(4)
memory usage: 5.8 KB

In [91]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  149 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB

In [96]:
new_df.fillna(0) # 평균을 구할 때는 평균을 넣으면 제이터 계산 시 지장이 없고, 온도,센서 경우는 1초 전과 크게 다르지 않으니 앞.뒤의 값을 갖다써도 크게 지장 없음.

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             0.0          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [93]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  149 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
dtypes: float64(4)
memory usage: 4.8 KB